language: node_js
node_js:
  - "12.13.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
before_install:
  - export TZ=America/Los_Angeles
script:
  - date
  - npm install
  - npm run lint
  - npm run test-headless
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//06j1LTRePo701CgYIARAAGAYSNwF-L9IrQyZ5IRK8KH1wHi8xh5sqT-92dkyNUdD9BIKuVg8z14cWE-fw-GaXUqmQi8ag_uX9JT0"