language: node_js
node_js:
  - "12.13.0"
addons:
  chrome: stable
  apt: 
    packages: 
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
before_install:
  - export TZ=America/Los_Angeles
script:
  - npm install
  - npm run lint
  - npm run test:ci
  - npm run build
  - npm run e2e:ci
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN