language: node_js
node_js:
  - "12.13.0"
dist: trusty
addons:
  chrome: stable
  apt: 
    packages: 
      - libgconf-2-4
  sonarcloud:
    organization: "bwhiting2356"
    token:
      secure: "seIyGebn1XEqJMyDqG1FzH2Vf5BWefYq8/2vW2JhOrXxjKO4DCyRwj6KraL8PnBJTYEO0htUWm0826e3S5Q2VlvElX4+FDb8tazvTGaWZL6XopOjcThpzE1by0Gllbn6xzMqzXV7t2UMc3uqaTWDOVHJXl89qNo++0k6tIf51Qc6nxH/ri/BpRL6ws6ORLNnU3fqQNar4oiwxrxDpggwvMrIRo9ULdpAiWoyd7OzyEfUJBe53RXtytJwDdRGcjqsI21U5RkeXO9qTk86lAN2oqsoKMKgz5UICCLAb0Efh/BpfKSzr3DUgtCwmOplHEC0m56o1cZqodFzSZZZQQeJu14+wOKocBXq2u4pw1r/YA6QdUNHozS8ec6Hkcf6Zy70rFm/UUOwF51FPVOClm+uGzUr7HfT1Tv+BrPy8aYkWnNx0hk9BXGiCUPvGlC5rzUFRWduyI4VGPysajxiFasNt1J4QW3qb0fjs7brauFtjuOHFK69xl0h1cWrpydG/EZcr052IWA1gy0rfDGXRMbw3nRz5cgc2V7p/4m2QRvjbCC9qxC0sE9lD1V0KirrHQd8oFJUUwKH/7Tb1iS9nwEhPWGEBDNj/D5XgEHLTf4EtBIJ1tuN1D8VhjJ/SnXmHIlBgzkB8RxpKWR7ThxmjwuylvaNGfm8buNpE/itBQ9Zji4="
 
cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
before_install:
  - export TZ=America/Los_Angeles
script:
  - npm install
  - npm run ci:all
  - sonar-scanner -X
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN